source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Gateway related
gem 'rerun'
gem 'aws-sdk-sqs'
gem 'aws-sdk-sns'
gem 'eventmachine'

# From App
gem 'pg'
gem 'redis'
gem 'bson_ext'
gem 'mongoid'
gem 'activerecord'
gem 'activesupport'