source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

# Infraestructure
gem 'rails', '~> 6.0.3', '>= 6.0.3.4'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 4.1'
gem 'mongoid', '~> 7.0.5'
gem 'aws-sdk-sns'

# Security
gem 'jwt'
gem 'device'

# GraphQL
gem 'graphql'
gem 'graphql-batch'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

# Debug
group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

# Docker hot-reload
group :development do
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
	gem 'graphiql-rails', '~> 1.4.8'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]